import { PatientRecord } from '../types';

const SAMPLE_FACE_PHOTO = 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="%23f1f5f9"/><circle cx="200" cy="120" r="60" fill="%23cbd5e1"/><path d="M120 280 C120 200, 280 200, 280 280 Z" fill="%2394a3b8"/><text x="200" y="290" text-anchor="middle" font-family="sans-serif" font-size="12" fill="%23475569">Frontal Photograph (Rest)</text></svg>';
const SAMPLE_INTRAORAL_PHOTO = 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="%23fff1f2"/><path d="M 80 150 Q 200 80 320 150 Q 200 220 80 150" fill="none" stroke="%23e11d48" stroke-width="8"/><text x="200" y="155" text-anchor="middle" font-family="sans-serif" font-size="14" font-weight="bold" fill="%239f1239">Anterior Occlusion View</text></svg>';
const SAMPLE_OPG_PHOTO = 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="%230f172a"/><text x="200" y="140" text-anchor="middle" font-family="sans-serif" font-size="16" font-weight="bold" fill="%2338bdf8">OPG Radiograph</text><text x="200" y="170" text-anchor="middle" font-family="sans-serif" font-size="12" fill="%2394a3b8">Panoramic Radiograph - All Permanent Teeth Present</text></svg>';

export const SAMPLE_PATIENTS: PatientRecord[] = [
  {
    id: 'sample-p1',
    patientId: 'ORTHO-2026-001',
    name: 'Ananya Deshmukh',
    age: 19,
    gender: 'Female',
    examDate: '2026-07-15',
    contact: '+91 98230 45112',
    email: 'ananya.d@gmail.com',
    archived: false,
    createdAt: '2026-07-15T10:00:00.000Z',
    updatedAt: '2026-07-28T14:20:00.000Z',
    chiefComplaint: {
      irregularTeeth: true,
      protrudingTeeth: true,
      spacing: false,
      missingTeeth: false,
      jawProblem: false,
      facialAesthetics: true,
      otherText: '',
      duration: '1-3 years',
      additionalNotes: 'Wants forward teeth aligned and corrected before college graduation.',
    },
    medicalHistory: {
      diabetes: false,
      hypertension: false,
      asthma: false,
      allergy: false,
      bleedingDisorder: false,
      otherMedical: false,
      noSignificantHistory: true,
      medicalNotes: 'Fit for elective orthodontic appliance therapy.',
    },
    dentalHistory: {
      previousExtraction: false,
      previousOrtho: false,
      trauma: false,
      restoration: true,
      dentalNotes: 'Class I Composite restoration on 36 occlusal.',
    },
    habitHistory: {
      thumbSucking: false,
      mouthBreathing: false,
      tongueThrusting: false,
      lipHabit: false,
      bruxism: false,
      none: true,
    },
    historySection: {
      informer: 'Self & Mother',
      prenatalMotherCondition: 'Uneventful pregnancy, full-term',
      deliveryType: 'Normal Vaginal',
      postnatalFeeding: 'Breastfed till 12 months',
      postnatalMilestones: 'Normal motor & speech milestones',
      behavioralHistory: 'Cooperative, well-motivated',
      socialHistory: 'College student, high aesthetic concern',
      childhoodDiseases: 'None reported',
      motivationForTreatment: 'Internal',
      attitudeTowardsTreatment: 'Enthusiastic',
      otherPertinentInfo: 'Prefers clear ceramic or invisible brackets if possible',
    },
    extraoralProfile: {
      built: 'Average',
      heightCm: 162,
      weightKg: 54,
      gait: 'Normal',
      bodyType: 'Mesomorph',
      facialIndex: 'Leptoprosopic',
      cephalicIndex: 'Mesocephalic',
      shapeOfHead: 'Mesocephalic',
      facialForm: 'Leptoprosopic',
      symmetry: 'Symmetrical',
      maxillaryMidline: 'Coincident with facial midline',
      mandibularMidline: 'Shifted 1mm right',
      lipPostureTonicity: 'Incompetent',
      interlabialGapMm: 4,
      incisorStomionMm: 3,
      profile: 'Convex',
      facialDivergence: 'Straight',
      nasolabialAngle: 'Acute',
      mentolabialSulcus: 'Deep',
      clinicalFma: 'Average (25°)',
      vto: 'Positive (Lip competence improves on mandibular advancement)',
    },
    functionalTmj: {
      respiration: 'Nasal',
      speech: 'Normal clear speech',
      mastication: 'Bilateral',
      swallowing: 'Mature swallow pattern',
      painHistory: false,
      clicking: false,
      crepitus: false,
      tendernessPalpation: false,
      pathOfClosure: 'Straight uninhibited closure',
      deviation: 'None',
      coCrDiscrepancy: 'Minimal (< 1mm)',
      maxOpeningMm: 45,
      freewaySpaceMm: 2,
    },
    intraoralSection: {
      tongueSize: 'Normal',
      tonguePosture: 'Normal resting posture',
      periodontalStatus: 'Healthy gingiva, good hygiene',
      brushingHabit: 'Twice daily',
      overallPeriodontal: 'Good',
      frenalAttachments: 'Normal',
      oralMucosa: 'Pink, moist, healthy',
      cariesTeeth: 'None active',
      missingTeeth: 'None',
      supernumeraryTeeth: 'None',
      impactedTeeth: 'Third molars erupting',
      toothColourTexture: 'Normal shade A2',
      toothShapeSizeForm: 'Normal anatomically',
      localizedAbnormalities: 'None',
      incisorRelation: 'Class II',
      canineRelationRight: 'Class II',
      canineRelationLeft: 'Class II',
      buccalOcclusionRight: 'Class II',
      buccalOcclusionLeft: 'Class II',
      curveOfSpeeMm: 2.5,
      overjetMm: 7,
      overbiteMm: 5,
      crossbite: 'None',
      displacements: 'Moderate lower anterior crowding',
      archFormUpper: 'U-shaped',
      archFormLower: 'U-shaped',
      archInadequacies: 'Arch length deficiency 4mm upper',
      archSymmetry: 'Symmetrical',
      midlineUpper: 'Coincident',
      midlineLower: '1mm Right',
      midlineTogether: '1mm discrepancy',
    },
    radiographyGrowth: {
      opgFindings: 'All 32 teeth present. Developing 18, 28, 38, 48.',
      lateralCephFindings: 'Skeletal Class II base, ANB = 6°, U1 to NA = 32°',
      iopaFindings: 'Normal alveolar bone levels',
      handWristFindings: 'SMI Stage 11 (Growth complete)',
      occlusalRadFindings: 'Normal palate anatomy',
      cvmStage: 'CS 6',
      pubertalStatus: 'Post-pubertal',
    },
    modelAnalysis: {
      maxillaryArchShape: 'U-shaped',
      mandibularArchShape: 'U-shaped',
      archSymmetry: 'Symmetrical',
      archAlignment: 'Crowding',
      individualIrregularities: 'Rotated 12 and 22',
      maxillaryArchLengthAvailable: 72,
      mandibularArchLengthAvailable: 66,
      premolarDiameter: 36,
      premolarBasalArchWidth: 41,
      measuredPremolarWidth: 35,
      measuredMolarWidth: 46,
      toothWidths: {
        '17': 9.5, '16': 10, '15': 7, '14': 7, '13': 7.5, '12': 7, '11': 8.5,
        '21': 8.5, '22': 7, '23': 7.5, '24': 7, '25': 7, '26': 10, '27': 9.5,
        '47': 9.5, '46': 10.5, '45': 7, '44': 7, '43': 6.5, '42': 5.5, '41': 5,
        '31': 5, '32': 5.5, '33': 6.5, '34': 7, '35': 7, '36': 10.5, '37': 9.5,
      },
    },
    investigations: {
      images: [
        {
          id: 'img-1',
          category: 'Extraoral Photo',
          title: 'Frontal View Rest',
          dataUrl: SAMPLE_FACE_PHOTO,
          uploadedAt: '2026-07-15T10:15:00.000Z',
        },
        {
          id: 'img-2',
          category: 'Intraoral Photo',
          title: 'Anterior Bite View',
          dataUrl: SAMPLE_INTRAORAL_PHOTO,
          uploadedAt: '2026-07-15T10:16:00.000Z',
        },
        {
          id: 'img-3',
          category: 'OPG',
          title: 'Pre-treatment OPG',
          dataUrl: SAMPLE_OPG_PHOTO,
          uploadedAt: '2026-07-15T10:18:00.000Z',
        },
      ],
      cephalometricSummary: 'ANB: 6° (Skeletal Class II), SNA: 82°, SNB: 76°, IMPA: 98°, U1-NA: 32°',
      modelAnalysisSummary: 'Carey Analysis shows 4mm arch length deficiency in upper arch.',
    },
    diagnosisAndPlan: {
      provisionalDiagnosis: "Angle's Class II division 1 malocclusion on a Skeletal Class II base due to retrognathic mandible, with severe overjet and deep bite.",
      skeletalClassification: 'Skeletal Class II',
      dentalClassification: 'Class II division 1',
      softTissueNotes: 'Convex profile with incompetent lips.',
      treatmentObjectives: '1. Correct overjet and deep bite\n2. Achieve Class I molar and canine relation\n3. Improve facial aesthetics & lip competence',
      proposedAppliance: 'Fixed Preadjusted Edgewise Appliance (MBT 0.022" slot)',
      extractionPlan: 'Upper 1st, Lower 2nd',
      retentionPlan: 'Upper Hawley Appliance with anterior bite plane & Lower fixed bonded lingual retainer (3-3)',
    },
    completionStatus: {
      history: true,
      extraoralProfile: true,
      functionalTmj: true,
      intraoral: true,
      radiographyGrowth: true,
      modelAnalysis: true,
      overallPercentage: 100,
    },
  },
];
