export interface LandmarkDefinition {
  id: string;
  name: string;
  abbreviation: string;
  category: 'Cranial Base' | 'Skeletal Maxilla' | 'Skeletal Mandible' | 'Dental' | 'Soft Tissue';
  definition: string;
  anatomicalGuide: string;
  expectedRegion: {
    label: string;
    normalizedX: number; // 0 to 1 relative estimate on lateral ceph
    normalizedY: number; // 0 to 1 relative estimate on lateral ceph
  };
  analyses: string[];
}

export const CEPH_LANDMARKS: LandmarkDefinition[] = [
  {
    id: 'sella',
    name: 'Sella',
    abbreviation: 'S',
    category: 'Cranial Base',
    definition: 'Geometric center of the pituitary fossa (sella turcica) in the sphenoid bone.',
    anatomicalGuide: 'Locate the saddle-shaped depression in the sphenoid bone. Position the landmark at the visual center of the rounded fossa.',
    expectedRegion: { label: 'Mid-cranial base (center upper region)', normalizedX: 0.42, normalizedY: 0.28 },
    analyses: ['Steiner', 'Downs', 'Tweed', 'McNamara', 'Ricketts', 'Jarabak', 'Schwarz', 'Bjork', 'Sassouni'],
  },
  {
    id: 'nasion',
    name: 'Nasion',
    abbreviation: 'N',
    category: 'Cranial Base',
    definition: 'Most anterior point of the frontonasal suture in the midline.',
    anatomicalGuide: 'Locate the notch at the junction between the frontal bone and nasal bones at the bridge of the nose.',
    expectedRegion: { label: 'Anterior cranial junction (upper right profile)', normalizedX: 0.65, normalizedY: 0.22 },
    analyses: ['Steiner', 'Downs', 'Tweed', 'McNamara', 'Ricketts', 'COGS', 'Jarabak', 'Schwarz', 'Bjork', 'Sassouni', 'Wits'],
  },
  {
    id: 'porion',
    name: 'Porion',
    abbreviation: 'Po',
    category: 'Cranial Base',
    definition: 'Superior-most point of the anatomical external auditory meatus.',
    anatomicalGuide: 'Identify the circular radiolucency of the external auditory meatus posterior to the condyle. Mark the top margin.',
    expectedRegion: { label: 'Posterior upper region (near ear canal)', normalizedX: 0.22, normalizedY: 0.35 },
    analyses: ['Downs', 'Tweed', 'McNamara', 'Ricketts', 'Schwarz'],
  },
  {
    id: 'orbitale',
    name: 'Orbitale',
    abbreviation: 'Or',
    category: 'Cranial Base',
    definition: 'Lowest point on the inferior radiopaque border of the orbital floor.',
    anatomicalGuide: 'Trace the lower curved boundary of the bony orbit and mark the lowest inferior point.',
    expectedRegion: { label: 'Inferior orbital rim (below eye socket)', normalizedX: 0.55, normalizedY: 0.32 },
    analyses: ['Downs', 'Tweed', 'McNamara', 'Ricketts'],
  },
  {
    id: 'basion',
    name: 'Basion',
    abbreviation: 'Ba',
    category: 'Cranial Base',
    definition: 'Most inferior-posterior point of the anterior margin of the foramen magnum.',
    anatomicalGuide: 'Locate the tip of the clivus / anterior tip of the foramen magnum near the posterior base of skull.',
    expectedRegion: { label: 'Posterior cranial base', normalizedX: 0.32, normalizedY: 0.42 },
    analyses: ['Downs', 'McNamara', 'Ricketts', 'Jarabak', 'Bjork'],
  },
  {
    id: 'articulare',
    name: 'Articulare',
    abbreviation: 'Ar',
    category: 'Cranial Base',
    definition: 'Point of intersection of the posterior shadow of the mandibular condyle and inferior border of the occipital bone.',
    anatomicalGuide: 'Find where the posterior contour of the condylar neck crosses the basilar part of the occipital bone.',
    expectedRegion: { label: 'Posterior condylar intersection', normalizedX: 0.25, normalizedY: 0.40 },
    analyses: ['COGS', 'Jarabak', 'Bjork'],
  },
  {
    id: 'pt_point',
    name: 'Pterygomaxillary Point',
    abbreviation: 'Pt',
    category: 'Cranial Base',
    definition: 'Intersection of the inferior border of the foramen rotundum with the posterior wall of the pterygomaxillary fissure.',
    anatomicalGuide: 'Locate the teardrop-shaped pterygomaxillary fissure. Mark its superior-posterior apex.',
    expectedRegion: { label: 'Superior apex of pterygomaxillary fissure', normalizedX: 0.40, normalizedY: 0.35 },
    analyses: ['Ricketts'],
  },
  {
    id: 'condylon',
    name: 'Condylon',
    abbreviation: 'Co',
    category: 'Skeletal Mandible',
    definition: 'Most superior-posterior point on the head of the mandibular condyle.',
    anatomicalGuide: 'Trace the curved top contour of the condylar head inside the glenoid fossa.',
    expectedRegion: { label: 'Top of mandibular condyle', normalizedX: 0.26, normalizedY: 0.38 },
    analyses: ['McNamara', 'COGS'],
  },
  {
    id: 'xi_point',
    name: 'Xi Point',
    abbreviation: 'Xi',
    category: 'Skeletal Mandible',
    definition: 'Geometric center of the ramus of the mandible.',
    anatomicalGuide: 'Located at the intersection of the diagonals constructed from R1, R2, R3, R4 of the ramus.',
    expectedRegion: { label: 'Center of mandibular ramus', normalizedX: 0.28, normalizedY: 0.52 },
    analyses: ['Ricketts'],
  },
  {
    id: 'ans',
    name: 'Anterior Nasal Spine',
    abbreviation: 'ANS',
    category: 'Skeletal Maxilla',
    definition: 'Tip of the bony anterior nasal spine at the inferior border of the nasal cavity.',
    anatomicalGuide: 'Locate the sharp anterior bony projection of the maxilla at the base of the nasal cavity.',
    expectedRegion: { label: 'Anterior maxillary projection', normalizedX: 0.62, normalizedY: 0.45 },
    analyses: ['McNamara', 'COGS', 'Sassouni', 'Schwarz'],
  },
  {
    id: 'pns',
    name: 'Posterior Nasal Spine',
    abbreviation: 'PNS',
    category: 'Skeletal Maxilla',
    definition: 'Tip of the posterior nasal spine of the palatine bone at the hard palate border.',
    anatomicalGuide: 'Trace the horizontal hard palate posteriorly to its sharp pointed end in the nasopharynx.',
    expectedRegion: { label: 'Posterior hard palate tip', normalizedX: 0.38, normalizedY: 0.46 },
    analyses: ['McNamara', 'COGS', 'Sassouni', 'Schwarz'],
  },
  {
    id: 'point_a',
    name: 'Point A (Subspinale)',
    abbreviation: 'A',
    category: 'Skeletal Maxilla',
    definition: 'Deepest midline point on the anterior concavity of the premaxilla between ANS and prosthion.',
    anatomicalGuide: 'Find the deepest incurvated point on the bony concavity below ANS above the central incisor roots.',
    expectedRegion: { label: 'Anterior maxillary concavity', normalizedX: 0.61, normalizedY: 0.50 },
    analyses: ['Steiner', 'Downs', 'McNamara', 'Ricketts', 'COGS', 'Schwarz', 'Wits'],
  },
  {
    id: 'point_b',
    name: 'Point B (Supramentale)',
    abbreviation: 'B',
    category: 'Skeletal Mandible',
    definition: 'Deepest midline point on the anterior concavity of the mandibular symphysis profile.',
    anatomicalGuide: 'Find the deepest incurvated point between infradentale and the bony chin (pogonion).',
    expectedRegion: { label: 'Anterior mandibular concavity', normalizedX: 0.58, normalizedY: 0.62 },
    analyses: ['Steiner', 'Downs', 'Tweed', 'McNamara', 'Ricketts', 'COGS', 'Schwarz', 'Wits'],
  },
  {
    id: 'pogonion',
    name: 'Pogonion',
    abbreviation: 'Pog',
    category: 'Skeletal Mandible',
    definition: 'Most anterior point of the bony chin in the median sagittal plane.',
    anatomicalGuide: 'Trace the anterior outline of the chin symphysis and mark the most prominent anterior point.',
    expectedRegion: { label: 'Anterior bony chin', normalizedX: 0.60, normalizedY: 0.70 },
    analyses: ['Steiner', 'Downs', 'Ricketts', 'Holdaway'],
  },
  {
    id: 'gnathion',
    name: 'Gnathion',
    abbreviation: 'Gn',
    category: 'Skeletal Mandible',
    definition: 'Most anterior-inferior point on the contour of the bony chin symphysis.',
    anatomicalGuide: 'Located on the chin curvature halfway between Pogonion (most anterior) and Menton (most inferior).',
    expectedRegion: { label: 'Antero-inferior chin curvature', normalizedX: 0.58, normalizedY: 0.74 },
    analyses: ['Steiner', 'Downs', 'McNamara', 'Ricketts', 'Jarabak'],
  },
  {
    id: 'menton',
    name: 'Menton',
    abbreviation: 'Me',
    category: 'Skeletal Mandible',
    definition: 'Most inferior point on the lowest border of the mandibular symphysis.',
    anatomicalGuide: 'Find the lowest bottom point on the outline of the bony chin symphysis.',
    expectedRegion: { label: 'Lowest point of bony chin', normalizedX: 0.56, normalizedY: 0.77 },
    analyses: ['Tweed', 'McNamara', 'COGS', 'Jarabak', 'Bjork', 'Sassouni'],
  },
  {
    id: 'gonion',
    name: 'Gonion',
    abbreviation: 'Go',
    category: 'Skeletal Mandible',
    definition: 'Most inferior-posterior point on the angle of the mandible.',
    anatomicalGuide: 'Bisect the angle formed by tangents to the posterior ramus and inferior mandibular plane.',
    expectedRegion: { label: 'Posterior-inferior jaw angle', normalizedX: 0.28, normalizedY: 0.68 },
    analyses: ['Steiner', 'Downs', 'Tweed', 'COGS', 'Jarabak', 'Bjork', 'Sassouni'],
  },
  {
    id: 'supra_pogonion',
    name: 'Supra-Pogonion (Pm)',
    abbreviation: 'Pm',
    category: 'Skeletal Mandible',
    definition: 'Point where the curvature of the anterior border of the symphysis changes from concave to convex.',
    anatomicalGuide: 'Located between Point B and Pogonion at the inflection point of the chin curve.',
    expectedRegion: { label: 'Inflection point on anterior chin', normalizedX: 0.59, normalizedY: 0.66 },
    analyses: ['Ricketts'],
  },
  {
    id: 'u1_tip',
    name: 'Upper Incisor Tip',
    abbreviation: 'U1T',
    category: 'Dental',
    definition: 'Incisal edge tip of the most anterior maxillary central incisor.',
    anatomicalGuide: 'Mark the sharpest tip of the incisal edge of the prominent upper central incisor.',
    expectedRegion: { label: 'Maxillary incisor edge', normalizedX: 0.58, normalizedY: 0.54 },
    analyses: ['Steiner', 'Downs', 'Tweed', 'McNamara', 'Ricketts', 'COGS', 'Holdaway'],
  },
  {
    id: 'u1_apex',
    name: 'Upper Incisor Apex',
    abbreviation: 'U1A',
    category: 'Dental',
    definition: 'Root apex of the most anterior maxillary central incisor.',
    anatomicalGuide: 'Follow the root canal outline of the upper central incisor superiorly to its apical tip.',
    expectedRegion: { label: 'Maxillary incisor root tip', normalizedX: 0.55, normalizedY: 0.48 },
    analyses: ['Steiner', 'Downs', 'Tweed', 'McNamara', 'Ricketts', 'COGS'],
  },
  {
    id: 'l1_tip',
    name: 'Lower Incisor Tip',
    abbreviation: 'L1T',
    category: 'Dental',
    definition: 'Incisal edge tip of the most anterior mandibular central incisor.',
    anatomicalGuide: 'Mark the incisal tip of the lower central incisor in occlusal contact or near upper incisor.',
    expectedRegion: { label: 'Mandibular incisor edge', normalizedX: 0.56, normalizedY: 0.55 },
    analyses: ['Steiner', 'Downs', 'Tweed', 'McNamara', 'Ricketts', 'COGS', 'Holdaway'],
  },
  {
    id: 'l1_apex',
    name: 'Lower Incisor Apex',
    abbreviation: 'L1A',
    category: 'Dental',
    definition: 'Root apex of the most anterior mandibular central incisor.',
    anatomicalGuide: 'Trace the mandibular central incisor root down into the symphysis to its apical tip.',
    expectedRegion: { label: 'Mandibular incisor root tip', normalizedX: 0.54, normalizedY: 0.63 },
    analyses: ['Steiner', 'Downs', 'Tweed', 'McNamara', 'Ricketts', 'COGS'],
  },
  {
    id: 'u6_mesial',
    name: 'Upper First Molar Crown',
    abbreviation: 'U6M',
    category: 'Dental',
    definition: 'Mesial contact point / cusp tip of the maxillary first permanent molar.',
    anatomicalGuide: 'Locate the mesial occlusal contact or cusp tip of the upper first permanent molar.',
    expectedRegion: { label: 'Upper molar crown', normalizedX: 0.42, normalizedY: 0.55 },
    analyses: ['Ricketts', 'COGS'],
  },
  {
    id: 'l6_mesial',
    name: 'Lower First Molar Crown',
    abbreviation: 'L6M',
    category: 'Dental',
    definition: 'Mesial contact point / cusp tip of the mandibular first permanent molar.',
    anatomicalGuide: 'Locate the mesial occlusal contact or cusp tip of the lower first permanent molar.',
    expectedRegion: { label: 'Lower molar crown', normalizedX: 0.41, normalizedY: 0.57 },
    analyses: ['Ricketts', 'COGS'],
  },
  {
    id: 'occ_anterior',
    name: 'Occlusal Plane Anterior',
    abbreviation: 'OccAnt',
    category: 'Dental',
    definition: 'Midpoint of the overlap of the incisors or contact point of premolars/canines.',
    anatomicalGuide: 'Mark the anterior reference point for constructing the functional occlusal plane.',
    expectedRegion: { label: 'Anterior occlusal contact', normalizedX: 0.57, normalizedY: 0.55 },
    analyses: ['Steiner', 'Downs', 'Wits'],
  },
  {
    id: 'occ_posterior',
    name: 'Occlusal Plane Posterior',
    abbreviation: 'OccPost',
    category: 'Dental',
    definition: 'Midpoint of the occlusal contact between the upper and lower first molars.',
    anatomicalGuide: 'Mark the posterior intercuspation contact point between upper and lower molars.',
    expectedRegion: { label: 'Posterior molar occlusion', normalizedX: 0.42, normalizedY: 0.56 },
    analyses: ['Steiner', 'Downs', 'Wits'],
  },
  {
    id: 'soft_nasion',
    name: 'Soft Tissue Nasion',
    abbreviation: "N'",
    category: 'Soft Tissue',
    definition: 'Point of deepest concavity in the soft tissue skin contour over the nasion region.',
    anatomicalGuide: 'Trace the skin profile over the bridge of the nose to its deepest incurvation.',
    expectedRegion: { label: 'Skin profile over nasal bridge', normalizedX: 0.68, normalizedY: 0.22 },
    analyses: ['Holdaway', 'Soft Tissue Profile'],
  },
  {
    id: 'pronasale',
    name: 'Pronasale',
    abbreviation: 'Prn',
    category: 'Soft Tissue',
    definition: 'Most prominent anterior point of the tip of the nose.',
    anatomicalGuide: 'Locate the peak anterior projection of the nasal tip profile.',
    expectedRegion: { label: 'Tip of nose profile', normalizedX: 0.78, normalizedY: 0.38 },
    analyses: ['Steiner', 'Holdaway', 'Ricketts E-Line'],
  },
  {
    id: 'subnasale_soft',
    name: 'Subnasale (Soft Tissue)',
    abbreviation: 'Sn',
    category: 'Soft Tissue',
    definition: 'Point where the lower border of the nasal septum meets the upper lip in the soft tissue profile.',
    anatomicalGuide: 'Mark the junction where the columella of the nose merges into the cutaneous upper lip.',
    expectedRegion: { label: 'Naso-labial soft tissue junction', normalizedX: 0.67, normalizedY: 0.48 },
    analyses: ['Steiner', 'Holdaway', 'Arnett'],
  },
  {
    id: 'labiale_superius',
    name: 'Labiale Superius',
    abbreviation: 'Ls',
    category: 'Soft Tissue',
    definition: 'Most anterior point of the upper lip vermilion margin.',
    anatomicalGuide: 'Locate the peak anterior point on the curvature of the upper lip.',
    expectedRegion: { label: 'Upper lip vermilion tip', normalizedX: 0.69, normalizedY: 0.52 },
    analyses: ['Steiner', 'Holdaway', 'Ricketts E-Line'],
  },
  {
    id: 'labiale_inferius',
    name: 'Labiale Inferius',
    abbreviation: 'Li',
    category: 'Soft Tissue',
    definition: 'Most anterior point of the lower lip vermilion margin.',
    anatomicalGuide: 'Locate the peak anterior point on the curvature of the lower lip.',
    expectedRegion: { label: 'Lower lip vermilion tip', normalizedX: 0.67, normalizedY: 0.58 },
    analyses: ['Steiner', 'Holdaway', 'Ricketts E-Line'],
  },
  {
    id: 'soft_pogonion',
    name: 'Soft Tissue Pogonion',
    abbreviation: "Pog'",
    category: 'Soft Tissue',
    definition: 'Most anterior point of the soft tissue chin profile.',
    anatomicalGuide: 'Trace the skin outline over the bony chin to its most prominent anterior point.',
    expectedRegion: { label: 'Soft tissue chin peak', normalizedX: 0.64, normalizedY: 0.70 },
    analyses: ['Steiner', 'Holdaway', 'Ricketts E-Line'],
  },
  {
    id: 'soft_menton',
    name: 'Soft Tissue Menton',
    abbreviation: "Me'",
    category: 'Soft Tissue',
    definition: 'Most inferior point of the soft tissue chin profile.',
    anatomicalGuide: 'Locate the lowest point on the skin outline beneath the chin.',
    expectedRegion: { label: 'Lowest soft tissue chin border', normalizedX: 0.58, normalizedY: 0.79 },
    analyses: ['Soft Tissue Profile'],
  },
  {
    id: 'columella',
    name: 'Columella Point',
    abbreviation: 'Cm',
    category: 'Soft Tissue',
    definition: 'Midpoint of the lower border of the columella of the nose.',
    anatomicalGuide: 'Mark the midpoint along the lower edge of the columella between nasal tip and subnasale.',
    expectedRegion: { label: 'Columella of nose', normalizedX: 0.73, normalizedY: 0.43 },
    analyses: ['Holdaway'],
  },
  {
    id: 'throat_point',
    name: 'Throat Point',
    abbreviation: 'Th',
    category: 'Soft Tissue',
    definition: 'Intersection of the submental tissue plane and the neck throat plane.',
    anatomicalGuide: 'Locate the soft tissue corner where the chin-throat outline transitions into the vertical neck.',
    expectedRegion: { label: 'Submental throat junction', normalizedX: 0.40, normalizedY: 0.78 },
    analyses: ['Holdaway'],
  },
  {
    id: 'stomion_superius',
    name: 'Stomion Superius',
    abbreviation: 'StmS',
    category: 'Soft Tissue',
    definition: 'Lowest point on the upper lip vermilion border at the inter-labial gap.',
    anatomicalGuide: 'Mark the lowest point on the margin of the upper lip where it meets the stomion gap.',
    expectedRegion: { label: 'Interlabial upper lip margin', normalizedX: 0.66, normalizedY: 0.54 },
    analyses: ['Arnett', 'Soft Tissue Profile'],
  },
  {
    id: 'stomion_inferius',
    name: 'Stomion Inferius',
    abbreviation: 'StmI',
    category: 'Soft Tissue',
    definition: 'Highest point on the lower lip vermilion border at the inter-labial gap.',
    anatomicalGuide: 'Mark the highest point on the margin of the lower lip at the interlabial contact gap.',
    expectedRegion: { label: 'Interlabial lower lip margin', normalizedX: 0.65, normalizedY: 0.55 },
    analyses: ['Arnett', 'Soft Tissue Profile'],
  },
  {
    id: 'antegonial_notch',
    name: 'Antegonial Notch',
    abbreviation: 'Ag',
    category: 'Skeletal Mandible',
    definition: 'Deepest point of the antegonial concavity on the inferior border of the mandible.',
    anatomicalGuide: 'Trace the inferior border of the mandibular body anterior to the angle to its deepest notch.',
    expectedRegion: { label: 'Antegonial notch on lower jaw', normalizedX: 0.38, normalizedY: 0.72 },
    analyses: ['Ricketts', 'Jarabak'],
  },
];
